### ISSUE TITLE
Error in the description aREST binary sensor

### ISSUE THREAD

**Issue by Rus-L** [balloob/home-assistant.io#151]
```yaml
# Example configuration.yaml entry
sensor:
  platform: arest
  resource: http://IP_ADDRESS
  name: Office Switch
  pin: 8
```
must be so:
```yaml
# Example configuration.yaml entry
binary_sensor:
  platform: arest
  resource: http://IP_ADDRESS
  name: Office Switch
  pin: 8
```
