### ISSUE TITLE
Blog post announcing IFTTT

### ISSUE THREAD

**Issue by balloob** [balloob/home-assistant.io#45]
The 0.7.2. release is out but not announced yet, as I want the announcement on the blog to be full of examples how to get started with IFTTT.

Examples how other services have announced it:
 - [Weebly](http://www.weebly.com/blog/powerful-new-connections-for-your-site-store-or-blog-with-ifttt-integration)
 - [Trello](http://blog.trello.com/if-this-then-trello/)
 - [Office365](https://blogs.office.com/2015/07/21/office-365-channels-are-live-on-ifttt/)

I've already made a graphic that we can use in our blog. This will also show up in the previews on FB/Twitter etc.

![ifttt](https://cloud.githubusercontent.com/assets/1444314/9779281/149afcdc-572f-11e5-82e2-8b7bc02e19b7.png)

**Comment by sfam** [comment]
one example for incomming actions from IFTTT recipes is to use the weather channel to trigger something in HA:

![image](https://cloud.githubusercontent.com/assets/12089995/9802286/f4e567b4-5810-11e5-8525-36dc83c697e2.png)

**"If tomorrow’s forecast calls for rain, turn off irrigation system."**

The maker channel, should be setup like:

URL: `http://xxx.xxx.xxx.xxx:8123/api/services/switch/turn_off?api_password=xxxxxxxx`
METHOD: `POST`
CONTENT TYPE: `application/json`
BODY: `{ "entity_id": "switch.irrigation" }`

**Comment by sfam** [comment]
An example to use IFTTT trigger service is to setup a automation rule to tweet important info:

![image](https://cloud.githubusercontent.com/assets/12089995/9802599/6ca27420-5813-11e5-82f2-1d0e7d860a7d.png)

**Tweet a help message when fire alarm is triggered**

```yaml
automation:
  alias: Post a tweet when fire alarm is triggered
  
  platform: mqtt
  mqtt_topic: home/alarm/fire
  mqtt_payload: 'on'

  execute_service: ifttt.trigger
  service_data: {"event":"HA_FIRE_ALARM", "value1":"The fire alarm just triggered!"}
```

Setup Maker channel with event name `HA_FIRE_ALARM` and Twitter channel to tweet the message in `value1`
