### ISSUE TITLE
Clarification on the Device_Tracker

### ISSUE THREAD

**Issue by CCOSTAN** [balloob/home-assistant.io#63]
I want to update the graphic and description for the Device_tracker (https://home-assistant.io/components/device_tracker.html) but need to make sure both `home_interval` (in minutes) and `consider_home` (in seconds) are still valid options in the `configuration.yaml'

```yaml
device_tracker:
  platform: nmap_tracker
  hosts: 192.168.10.100-250
  home_interval: 30
  track_new_devices: no
  consider_home: 1800
```
